### ISSUE TITLE
Workflow abort fails to stop SGE jobs

### ISSUE THREAD

**Issue by rgobbel** [broadinstitute/cromwell#3259]
With Cromwell 30.2:

Attempting to abort a workflow mostly running on SGE triggers lots of these errors:

2018-02-09 11:52:46,500 cromwell-system-akka.dispatchers.engine-dispatcher-96 WARN  - unhandled event EngineLifecycleActorAbortCommand in state SubWorkflowRunningState

Queued and running SGE jobs continue as if nothing happened.

**Comment by Horneth** [comment]
This is indeed a bug. I'm looking into it. Thanks for reporting it !

**Comment by Horneth** [comment]
This has been fixed today in `develop` as well as hotfixed on the latest release branch (`30_hotfix`)
Thanks again for spotting it !

**Comment by rgobbel** [comment]
Thanks for super-quick response!

**Comment by rgobbel** [comment]
I've downloaded the new jar file, still showing version 30.2, but still seeing the problem in some situations:

2018-02-21 11:03:39,563 cromwell-system-akka.dispatchers.engine-dispatcher-95 INFO  - Abort requested for workflow f0bff6e2-77a6-46f5-b226-13a64339a286.
2018-02-21 11:03:39,564 cromwell-system-akka.dispatchers.engine-dispatcher-95 INFO  - WorkflowExecutionActor-f0bff6e2-77a6-46f5-b226-13a64339a286 [UUID(f0bff6e2)]: Aborting workflow
2018-02-21 11:03:39,567 cromwell-system-akka.dispatchers.engine-dispatcher-50 WARN  - unhandled event EngineLifecycleActorAbortCommand in state SubWorkflowRunningState

Several SGE queue jobs continue to run/stay in the queue waiting state.
